name: zeedata
description: "A production-ready VTU mobile app."
version: 1.0.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  font_awesome_flutter: ^10.6.0
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  local_auth: ^2.1.8
  share_plus: ^12.0.2
  path_provider: ^2.1.5
  screenshot: ^3.0.0
  url_launcher: ^6.3.2
  crypto: ^3.0.7
  flutter_native_contact_picker: ^0.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpeg"
  min_sdk_android: 21
